FROM ghcr.io/fuqiuluo/unidbg-fetch-qsign:master

ENV QQnum 2186345636
ENV QQpasswd ''
ENV groupNum 865727299
ENV gameId 3
ENV url http://nbal.nuc.edu.cn

WORKDIR /app

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt update -y
RUN apt install python3 python3-pip -y --fix-missing

RUN mkdir gzbot
COPY gzbot gzbot
RUN pip install -r gzbot/requirements.txt
COPY go-cqhttp.deb .
RUN apt install ./go-cqhttp.deb -y
COPY start.sh .

RUN chmod 777 start.sh && \
    sed -i "s/QQnum/$QQnum/g" ./gzbot/config.yml

EXPOSE 5700

CMD ./start.sh $url $groupNum $gameId